version: '3.4'

services:
  redis:
    image: redis:nanoserver
    ports:
      - 6379:6379

  webapplication2:
    image: ${DOCKER_REGISTRY}webapplication2
    build:
      context: .
      dockerfile: WebApplication2\Dockerfile
    depends_on:
      - redis
